apiVersion: v1
kind: PersistentVolume
metadata:
  name: matchup-prometheus-server-pv
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: matchup-prometheus
    app.kubernetes.io/name: prometheus
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus-server"
  persistentVolumeReclaimPolicy: Retain
