apiVersion: v1
kind: PersistentVolume
metadata:
  name: matchup-pv-alertmanager
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/prometheus
  persistentVolumeReclaimPolicy: Retain
