apiVersion: v1
kind: Service
metadata:
  name: mongodb-fcm-service
spec:
  selector:
    app: mongodb-fcm
  ports:
    - protocol: TCP
      port: 3314          # 외부에서 접근할 MongoDB 포트
      targetPort: 27017    # MongoDB가 사용하는 포트

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-fcm-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  selector:
    matchLabels:
      app: mongodb-fcm
  template:
    metadata:
      labels:
        app: mongodb-fcm
    spec:
      containers:
      - name: mongodb
        image: mongo:latest   # MongoDB 이미지
        ports:
        - containerPort: 27017    # MongoDB가 사용하는 포트
