apiVersion: v1
kind: Service
metadata:
  name: mongodb-chat-service
spec:
  selector:
    app: mongodb-chat
  ports:
    - protocol: TCP
      port: 3310          # 외부에서 접근할 MongoDB 포트
      targetPort: 27017    # MongoDB가 사용하는 포트

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/mongo/chat

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-chat-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  selector:
    matchLabels:
      app: mongodb-chat
  template:
    metadata:
      labels:
        app: mongodb-chat
    spec:
      containers:
      - name: mongodb
        image: mongo:latest   # MongoDB 이미지
        ports:
        - containerPort: 27017    # MongoDB가 사용하는 포트
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/mongo/chat
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
