apiVersion: v1
kind: Service
metadata:
  name: mongodb-statistics-service
spec:
  selector:
    app: mongodb-statistics
  ports:
    - protocol: TCP
      port: 3311
      targetPort: 27017

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-statistics-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/mongo/statistics

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-statistics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-statistics-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  selector:
    matchLabels:
      app: mongodb-statistics
  template:
    metadata:
      labels:
        app: mongodb-statistics
    spec:
      containers:
      - name: mongodb
        image: mongo:latest   # MongoDB 이미지
        ports:
        - containerPort: 27017    # MongoDB가 사용하는 포트
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/mongo/statistics
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-statistics-pvc
