apiVersion: v1
kind: Service
metadata:
  name: mongodb-learning-service
spec:
  selector:
    app: mongodb-learning
  ports:
    - protocol: TCP
      port: 3999
      targetPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-laerning-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  selector:
    matchLabels:
      app: mongodb-learning
  template:
    metadata:
      labels:
        app: mongodb-learning
    spec:
      containers:
      - name: mongodb
        image: mongo:latest   # MongoDB 이미지
        ports:
        - containerPort: 27017    # MongoDB가 사용하는 포트
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/mongo/statistics
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-statistics-pvc
