apiVersion: v1
kind: Service
metadata:
  name: mysql-user-service
spec:
  selector:
    app: mysql-user
  ports:
    - protocol: TCP
      port: 3308          # 외부에서 접근할 MongoDB 포트
      targetPort: 3308    # MongoDB가 사용하는 포트

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-user-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/mysql/user

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
      - name: mysql-user
        image: 1eaf/matchup_user:latest   # MongoDB 이미지
        ports:
        - containerPort: 3308    # MongoDB가 사용하는 포트
        volumeMounts:
        - name: mysql-user
          mountPath: /data/mysql/user
      volumes:
      - name: mysql-user
        persistentVolumeClaim:
          claimName: mysql-user-pvc
