apiVersion: v1
kind: Service
metadata:
  name: redis-user-service
spec:
  selector:
    app: redis-user
  ports:
    - protocol: TCP
      port: 3313         # 외부에서 접근할 MongoDB 포트
      targetPort: 6379    # MongoDB가 사용하는 포트

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-user-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  selector:
    matchLabels:
      app: redis-user
  template:
    metadata:
      labels:
        app: redis-user
    spec:
      containers:
      - name: redis-user
        image: redis   # MongoDB 이미지
        ports:
        - containerPort: 6379    # MongoDB가 사용하는 포트