apiVersion: v1
kind: Service
metadata:
  name: alarm-service
spec:
  selector:
    app: alarm-server
  ports:
    - protocol: TCP
      port: 9007
      targetPort: 9007

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-server-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: alarm-server
  template:
    metadata:
      labels:
        app: alarm-server
    spec:
      containers:
      - name: alarm-server
        image: 0710june/alarm-server:latest
        ports:
        - containerPort: 9007
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        - name: key-volume
          mountPath: /key
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: matchup-config
      - name: key-volume
        configMap:
          name: matchup-service-account-key