apiVersion: v1
kind: Service
metadata:
  name: bigdata-service
spec:
  selector:
    app: bigdata-server
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdata-server-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: bigdata-server
  template:
    metadata:
      labels:
        app: bigdata-server
    spec:
      containers:
      - name: bigdata-server
        image: 0710june/bigdata-server:latest
        ports:
        - containerPort: 9005
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: matchup-config
