apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-server
  ports:
    - protocol: TCP
      port: 9003          # 외부에서 접근할 포트
      targetPort: 9003    # 채팅 서버가 사용하는 포트

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
      - name: chat-server
        image: 0710june/chat-server:latest   # 채팅 서버 이미지
        ports:
        - containerPort: 9003    # 채팅 서버가 사용하는 포트
        resources:
          limits:
            cpu: "1000m"
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: matchup-config

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-server-deployment
  minReplicas: 1               # 최소 레플리카 수
  maxReplicas: 10              # 최대 레플리카 수
  targetCPUUtilizationPercentage: 80
