apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  selector:
    app: file-server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
      - name: file-server
        image: 0710june/file-server:latest
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: matchup-config
