apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-server
  ports:
    - protocol: TCP
      port: 9002          # 외부에서 접근할 포트
      targetPort: 9002    # 채팅 서버가 사용하는 포트

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
spec:
  replicas: 1             # 초기 레플리카 수
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-server
        image: 0710june/user-server:latest   # 채팅 서버 이미지
        ports:
        - containerPort: 9002    # 채팅 서버가 사용하는 포트
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: matchup-config