import "../../styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/providers";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import NavigationBar from "./ui/Navbar";
import SideBar from "./ui/Sidebar";
import { lusitana, tektur } from "./ui/fonts";
import { SessionProvider } from "next-auth/react";
// import SockJS from "sockjs-client";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "MATCHUP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // 페이지 또는 nested layout
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const sock = new SockJS("http://localhost:3000")
  // sock.onopen = function() {
  //   console.log('open');
  //   sock.send('test');
  // };

  // sock.onmessage = function(e) {
  //   console.log('message', e.data);
  //   sock.close();
  // };

  // sock.onclose = function() {
  //   console.log('close');
  // };

  return (
    <html lang="en" className="dark">
      <body className={tektur.className}>
        <Providers>
          <AntdRegistry>
            <NavigationBar />
            <div className="layout-container">
              <SideBar />
              <div className="main-content">
                {children}
              </div>
            </div>
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
