export default function Data() {
}

export const demoArticles = [
  {
    id: 1,
    title: "이게 솔직히 내 잘못이냐?",
    content: "미안하다 이거 보여주려고 어그로끌었다.. \n나루토 사스케 싸움수준 ㄹㅇ실화냐? \n진짜 세계관최강자들의 싸움이다.. \n그찐따같던 나루토가 맞나? 진짜 나루토는 전설이다..\n진짜옛날에 맨날나루토봘는데 왕같은존재인 호카게 되서 세계최강 전설적인 영웅이된나루토보면 진짜내가다 감격스럽고 나루토 노래부터 명장면까지 가슴울리는장면들이 뇌리에 스치면서 가슴이 웅장해진다..",
    video_url: null,
    thumbnail_url: "https://i.namu.wiki/i/4Wk8LbzlFWWX3ux1IXBLy9-bdR1hkJ-QaOgJmYBasPqYW4ZiAtomvLC5WM6KtZ-VvpYuWMpuNpnsTf3qbUyYI6YRInKBkLKvpMlA0F37MI5JzmjIY57AcMMDtgISkw1FhgkuwIPU_q7Z_SB9m4QDpQ.webp",
    author: "T1 티모석",
    views: 7092,
    left_sympathy_title: "정글 잘못",
    right_sympathy_title: "탑 잘못",
    left_sympathy_count: 7,
    right_sympathy_count: 3,
    left_sympathy_percent: 70,
    right_sympathy_percent: 30
  },
  {
    id: 2,
    title: "20만원 빵 내기 중임... 투표 좀",
    content: "이 편지는 영국에서 최초로 시작되어 일년에 한바퀴를 돌면서 받는 사람에게 행운을 주었고 지금은 당신에게로 옮겨진 이 편지는 4일 안에 당신 곁을 떠나야 합니다. \n이 편지를 포함해서 7통을 행운이 필요한 사람에게 보내 주셔야 합니다. \n복사를 해도 좋습니다. \n혹 미신이라 하실지 모르지만 사실입니다.",
    video_url: null,
    thumbnail_url: "https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Janna_0.jpg",
    author: "Gen Sumin",
    views: 16738,
    left_sympathy_title: "숟가락 차이",
    right_sympathy_title: "도구 차이",
    left_sympathy_count: 3,
    right_sympathy_count: 7,
    left_sympathy_percent: 30,
    right_sympathy_percent: 70
  },
  {
    id: 3,
    title: "이게 솔직히 내 잘못이냐?",
    content: "미안하다 이거 보여주려고 어그로끌었다.. \n나루토 사스케 싸움수준 ㄹㅇ실화냐? \n진짜 세계관최강자들의 싸움이다.. \n그찐따같던 나루토가 맞나? 진짜 나루토는 전설이다..\n진짜옛날에 맨날나루토봘는데 왕같은존재인 호카게 되서 세계최강 전설적인 영웅이된나루토보면 진짜내가다 감격스럽고 나루토 노래부터 명장면까지 가슴울리는장면들이 뇌리에 스치면서 가슴이 웅장해진다..",
    video_url: null,
    thumbnail_url: "https://i.namu.wiki/i/4Wk8LbzlFWWX3ux1IXBLy9-bdR1hkJ-QaOgJmYBasPqYW4ZiAtomvLC5WM6KtZ-VvpYuWMpuNpnsTf3qbUyYI6YRInKBkLKvpMlA0F37MI5JzmjIY57AcMMDtgISkw1FhgkuwIPU_q7Z_SB9m4QDpQ.webp",
    author: "T1 티모석",
    views: 7092,
    left_sympathy_title: "정글 잘못",
    right_sympathy_title: "탑 잘못",
    left_sympathy_count: 7,
    right_sympathy_count: 3,
    left_sympathy_percent: 70,
    right_sympathy_percent: 30
  },
  {
    id: 4,
    title: "20만원 빵 내기 중임... 투표 좀",
    content: "이 편지는 영국에서 최초로 시작되어 일년에 한바퀴를 돌면서 받는 사람에게 행운을 주었고 지금은 당신에게로 옮겨진 이 편지는 4일 안에 당신 곁을 떠나야 합니다. \n이 편지를 포함해서 7통을 행운이 필요한 사람에게 보내 주셔야 합니다. \n복사를 해도 좋습니다. \n혹 미신이라 하실지 모르지만 사실입니다.",
    video_url: null,
    thumbnail_url: "https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Janna_0.jpg",
    author: "Gen Sumin",
    views: 16738,
    left_sympathy_title: "숟가락 차이",
    right_sympathy_title: "도구 차이",
    left_sympathy_count: 3,
    right_sympathy_count: 7,
    left_sympathy_percent: 30,
    right_sympathy_percent: 70
  },
  {
    id: 5,
    title: "이게 솔직히 내 잘못이냐?",
    content: "미안하다 이거 보여주려고 어그로끌었다.. \n나루토 사스케 싸움수준 ㄹㅇ실화냐? \n진짜 세계관최강자들의 싸움이다.. \n그찐따같던 나루토가 맞나? 진짜 나루토는 전설이다..\n진짜옛날에 맨날나루토봘는데 왕같은존재인 호카게 되서 세계최강 전설적인 영웅이된나루토보면 진짜내가다 감격스럽고 나루토 노래부터 명장면까지 가슴울리는장면들이 뇌리에 스치면서 가슴이 웅장해진다..",
    video_url: null,
    thumbnail_url: "https://i.namu.wiki/i/4Wk8LbzlFWWX3ux1IXBLy9-bdR1hkJ-QaOgJmYBasPqYW4ZiAtomvLC5WM6KtZ-VvpYuWMpuNpnsTf3qbUyYI6YRInKBkLKvpMlA0F37MI5JzmjIY57AcMMDtgISkw1FhgkuwIPU_q7Z_SB9m4QDpQ.webp",
    author: "T1 티모석",
    views: 7092,
    left_sympathy_title: "정글 잘못",
    right_sympathy_title: "탑 잘못",
    left_sympathy_count: 7,
    right_sympathy_count: 3,
    left_sympathy_percent: 70,
    right_sympathy_percent: 30
  },
  {
    id: 6,
    title: "20만원 빵 내기 중임... 투표 좀",
    content: "이 편지는 영국에서 최초로 시작되어 일년에 한바퀴를 돌면서 받는 사람에게 행운을 주었고 지금은 당신에게로 옮겨진 이 편지는 4일 안에 당신 곁을 떠나야 합니다. \n이 편지를 포함해서 7통을 행운이 필요한 사람에게 보내 주셔야 합니다. \n복사를 해도 좋습니다. \n혹 미신이라 하실지 모르지만 사실입니다.",
    video_url: null,
    thumbnail_url: "https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Janna_0.jpg",
    author: "Gen Sumin",
    views: 16738,
    left_sympathy_title: "숟가락 차이",
    right_sympathy_title: "도구 차이",
    left_sympathy_count: 3,
    right_sympathy_count: 7,
    left_sympathy_percent: 30,
    right_sympathy_percent: 70
  },
  {
    id: 7,
    title: "이게 솔직히 내 잘못이냐?",
    content: "미안하다 이거 보여주려고 어그로끌었다.. \n나루토 사스케 싸움수준 ㄹㅇ실화냐? \n진짜 세계관최강자들의 싸움이다.. \n그찐따같던 나루토가 맞나? 진짜 나루토는 전설이다..\n진짜옛날에 맨날나루토봘는데 왕같은존재인 호카게 되서 세계최강 전설적인 영웅이된나루토보면 진짜내가다 감격스럽고 나루토 노래부터 명장면까지 가슴울리는장면들이 뇌리에 스치면서 가슴이 웅장해진다..",
    video_url: null,
    thumbnail_url: "https://i.namu.wiki/i/4Wk8LbzlFWWX3ux1IXBLy9-bdR1hkJ-QaOgJmYBasPqYW4ZiAtomvLC5WM6KtZ-VvpYuWMpuNpnsTf3qbUyYI6YRInKBkLKvpMlA0F37MI5JzmjIY57AcMMDtgISkw1FhgkuwIPU_q7Z_SB9m4QDpQ.webp",
    author: "T1 티모석",
    views: 7092,
    left_sympathy_title: "정글 잘못",
    right_sympathy_title: "탑 잘못",
    left_sympathy_count: 7,
    right_sympathy_count: 3,
    left_sympathy_percent: 70,
    right_sympathy_percent: 30
  },
  {
    id: 8,
    title: "20만원 빵 내기 중임... 투표 좀",
    content: "이 편지는 영국에서 최초로 시작되어 일년에 한바퀴를 돌면서 받는 사람에게 행운을 주었고 지금은 당신에게로 옮겨진 이 편지는 4일 안에 당신 곁을 떠나야 합니다. \n이 편지를 포함해서 7통을 행운이 필요한 사람에게 보내 주셔야 합니다. \n복사를 해도 좋습니다. \n혹 미신이라 하실지 모르지만 사실입니다.",
    video_url: null,
    thumbnail_url: "https://ddragon.leagueoflegends.com/cdn/img/champion/centered/Janna_0.jpg",
    author: "Gen Sumin",
    views: 16738,
    left_sympathy_title: "숟가락 차이",
    right_sympathy_title: "도구 차이",
    left_sympathy_count: 3,
    right_sympathy_count: 7,
    left_sympathy_percent: 30,
    right_sympathy_percent: 70
  }
]

export const demoLobbyChats = [
  {
    id: 1,
    profileIcon: "https://ddragon.leagueoflegends.com/cdn/14.5.1/img/profileicon/705.png",
    summonerName: "개나소나",
    summonerTag: "#KR1",
    myPosition: 4,
    tier: "P1",
    searchingPosition: 0,
    wins: 29,
    loses: 28,
    kill: 6.1,
    death: 6.3,
    assist: 6.9,
    memo: "멘탈 좋으신 서폿님 구해요"
  },
  {
    id: 2,
    profileIcon: "https://ddragon.leagueoflegends.com/cdn/14.5.1/img/profileicon/933.png",
    summonerName: "디건마스코트",
    summonerTag: "#KR1",
    myPosition: 1,
    tier: "D2",
    searchingPosition: 2,
    wins: 12,
    loses: 3,
    kill: 9.9,
    death: 3.2,
    assist: 4.9,
    memo: "원딜 정글 고수님 찾습니다!"
  },
  {
    id: 3,
    profileIcon: "https://ddragon.leagueoflegends.com/cdn/14.5.1/img/profileicon/1614.png",
    summonerName: "방식이",
    summonerTag: "#KR1",
    myPosition: 3,
    tier: "S3",
    searchingPosition: 1,
    wins: 64,
    loses: 74,
    kill: 2.1,
    death: 3.4,
    assist: 13.8,
    memo: "부캐 듀오 구합니다."
  },
  {
    id: 4,
    profileIcon: "https://ddragon.leagueoflegends.com/cdn/14.5.1/img/profileicon/3413.png",
    summonerName: "협곡테이저건",
    summonerTag: "#KR1",
    myPosition: 2,
    tier: "G2",
    searchingPosition: 3,
    wins: 182,
    loses: 180,
    kill: 9.8,
    death: 6.1,
    assist: 6.2,
    memo: "같이 골드 갈 분 멘탈 강하신 분 구해요"
  },
  {
    id: 5,
    profileIcon: "https://ddragon.leagueoflegends.com/cdn/14.5.1/img/profileicon/5637.png",
    summonerName: "베이가",
    summonerTag: "#KR12",
    myPosition: 5,
    tier: "E4",
    searchingPosition: 4,
    wins: 29,
    loses: 28,
    kill: 6.1,
    death: 6.3,
    assist: 6.9,
    memo: "마이크 되는 분 듀요해요"
  },
]

